{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fortio.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $servicePort := .Values.ingress.servicePort | default "http" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fortio.name" . }}
    chart: {{ template "fortio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if .Values.ingress.class.nginx }}
    kubernetes.io/ingress.class: nginx
    {{- end }}
    {{- if .Values.ingress.class.gce }}
    kubernetes.io/ingress.class: gce
    {{- end }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.existingSecret | default (include "fortio.tlsSecretName" .) }}
{{- end }}
  rules:
    - host:  {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ $ingressPath | default "/*" }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
{{- end }}