{{- $namespace := .Release.Namespace -}}
{{- $fullName := include "fortio.fullname" . -}}
{{- if not .Values.ingress.tls.existingSecret }}
{{- with .Values.defaultTLS }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-tls
  namespace: {{ $namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .cert }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}

{{- if not .Values.ingress.iap.existingSecret }}
{{- with .Values.defaultIAP }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-iap
  namespace: {{ $namespace }}
type: Opaque
data:
  client_id: {{ .client_id }}
  client_secret: {{ .client_secret }}
{{- end }}
{{- end }}
