{{- $namespace := .Release.Namespace -}}
{{- if .Values.tls.enabled }}
{{- with .Values.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: {{ $namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .cert }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}