##
## deployment configuration
replicaCount: 1

image:
  repository: gcr.io/nmiu-play/fortio
  tag: latest
  pullPolicy: Always

podSecurityPolicy:
  enabled: false

##
## Service configuration
service:
  enabled: true
  ##
  ## Service type (default to "NodePort")
  # type: ClusterIP
  type: LoadBalancer
  # type: NodePort
  ##
  ## External traffic policy (default to "Cluster")
  externalTrafficPolicy: Cluster
  # externalTrafficPolicy: Local
  ##
  ## Session affinity (default to "None")
  # sessionAffinity: None
  sessionAffinity: ClientIP

  ilb: 
    enabled: false
  headless: 
    enabled: false
  http2: 
    enabled: false