{{- $namespace := include "tiddles.tempNamespaceName" . }}
{{ if or .Values.backend.tls.enabled .Values.ingress.tls.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-creator-sa
  namespace: {{ $namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: secret-creator-sa-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: secret-creator-sa
    namespace: {{ $namespace }}
{{- end }}

{{ if .Values.backend.tls.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-backend-tls-secret
  namespace: {{ $namespace }}
spec:
  template:
    metadata:
      labels:
        job: create-backend-tls-secret
    spec:
      containers:
      - name: kubectl
        image: gcr.io/nmiu-play/kubectl:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        args:
          - /create_secret.sh
          - {{ template "tiddles.backendTLSSecretName" . }}
          - {{ .Release.Namespace }}
          - {{ template "tiddles.backend" . }}
      serviceAccountName: secret-creator-sa
      restartPolicy: Never
{{- end }}

{{ if .Values.ingress.enabled }}
{{ if and .Values.ingress.tls.enabled (not .Values.ingress.tls.existingSecret) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-ingress-tls-secret
  namespace: {{ $namespace }}
spec:
  template:
    metadata:
      labels:
        job: create-ingress-tls-secret
    spec:
      containers:
      - name: kubectl
        image: gcr.io/nmiu-play/kubectl:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        args:
          - /create_secret.sh
          - {{ template "tiddles.ingressTLSSecretName" . }}
          - {{ .Release.Namespace }}
          - {{ .Values.ingress.host }}
      serviceAccountName: secret-creator-sa
      restartPolicy: Never
{{- end }}
{{- end }}
